# Generated by Django 3.1.1 on 2020-11-22 17:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('about_us', models.TextField()),
                ('privacy_policy', models.TextField()),
                ('facebook', models.URLField(default='www.facebook.com')),
                ('instagram', models.URLField(default='www.instagram.com')),
                ('youtube', models.URLField(default='www.youtube.com')),
            ],
        ),
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drama_name', models.CharField(max_length=100)),
                ('famous_in_country', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('video_url', models.CharField(max_length=1000)),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('famous_in_city', models.CharField(max_length=100)),
                ('famous_in_country', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('district_name', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('video_url', models.CharField(max_length=1000)),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('district_name', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
